galasa-dev/integratedtests

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/AbstractCompilationLocal.java
> Increase timeout to 5 minutes for the gradle compile

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava11UbuntuRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava11UbuntuRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava11UbuntuRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava11UbuntuRse.java
> disabling RSE tests from codecoverage until they are reliable

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/local/DockerLocalJava11Ubuntu.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/local/DockerLocalJava16Ubuntu.java
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>
Removing the Docker integrated tests from the schedule for now, as they are causing the regression-run job as a whole to get stuck. They are also retrying multiple times, which is filling up galasa-prod with Pods. I will be investigating the problem with these tests and I will add back to the schedule once I have fixed them.
https://github.com/galasa-dev/projectmanagement/issues/1386
> Remove Docker integrated tests - Issue 1386

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/simbank/AbstractCompilationLocalSimBank.java
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>
See issue [Inttest failure : .gradle needs to be checked-in !#1645](https://github.com/galasa-dev/projectmanagement/issues/1645)
> simbank integration test should not insist that .gradle is checked-in to simbank repo. Create folder dynamically

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDocker.java
- galasa-inttests-parent/gradle.properties
- Experimenting to see if we can pull images from harbor.galasa.dev instead of harbor-cicsk8s for the DockerManager test.
- Also updated galasaVersion in gradle.properties but not entirely sure this is actually used.
> Iss1736 - Updating Docker registry to harbor.galasa.dev to remove harbor-cicsk8s dependency

- galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
Signed-off-by: Fiona Ampofo <64271621+Akyiaa@users.noreply.github.com>
Story: https://github.com/galasa-dev/projectmanagement/issues/1755
> correcting the maven plugin 'catatlog' typo

- build-locally.sh
- galasa-inttests-parent/build.gradle
- galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
- galasa-inttests-parent/dev.galasa.inttests/build.gradle
- galasa-inttests-parent/gradle.properties
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>
- Uplift plugins to 0.33.0
- Use the bom instead of specific versions of the managers.
> Uplift versions of galasa plugins used. Use the bom for dependency versions

- galasa-inttests-parent/build.gradle
- galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
- galasa-inttests-parent/dev.galasa.inttests/build.gradle
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/sdv/AbstractSDVLocal.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/sdv/local/SDVLocalJava11Ubuntu.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/sdv/local/isolated/SDVLocalJava11UbuntuIsolated.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/resources/offlinebuild/AllManagers.txt
- galasa-inttests-parent/gradle.properties
Adding the SDV Manager IVT to the IVT test suite.
Provides the required CPS properties for the test to run.
> Add SDV IVT to suite

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/sdv/AbstractSDVLocal.java
Changing test to use a dedicated region for the SDV IVT, using a DSE. This DSE has been set up in the prod ecosystem CPS, using the same APPLID as the zos3270 test. I'm using overrides to only temporarily set to DSE provisioning for this test only (its sem dy default currently).
The dedicated APPLID is at 730 at the moment, so this test will always pass as its essentially skipped. The dedicated region also has `SEC=NO`, which will cause this test to fail when it is eventually upgraded.
SDV IVT related changes are here https://github.com/galasa-dev/managers/pull/952
> use a dse region for sdv ivt

- .github/workflows/build.yaml
To fix the error found here: https://github.com/galasa-dev/obr/actions/runs/11125875809/job/30915007341
> allow main build to be called by workflow_dispatch

- galasa-inttests-parent/dev.galasa.inttests/src/main/resources/offlinebuild/AllManagers.txt
- galasa-inttests-parent/dev.galasa.inttests/src/main/resources/offlinebuild/MVPManagers.txt
For https://github.com/galasa-dev/projectmanagement/issues/2018 - to fix failure in CompilationLocalOfflineJava11UbuntuMVP test. CompilationLocalOfflineJava11UbuntuIsolated test isn't failing (not sure why as VTP Manager has also been removed from Isolated) but thought I'd clean up the AllManagers.txt while I was making this change.
> Iss2018 - removing managers from text file that are no longer in isolated/mvp

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDockerUbuntuLocal.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/AbstractZosBatchLocalRSE.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/AbstractZosFileLocalRSE.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/AbstractZosFileDatasetLocalRSE.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/AbstractZosVSAMLocalRSE.java
- Removing the `GitHubIssue` annotation from tests that no longer use it/the issue is closed therefore ignored
- Added the annotation to the RSE tests that are affected by the GitHub Issue 1961 so their result will be "Failed with Defects", so easier to pick out other failures in the daily regression run
> GitHub issue annotation

- galasa-inttests-parent/build.gradle
See https://github.com/galasa-dev/galasa/pull/54 and https://github.com/galasa-dev/galasa/pull/56
Reverting assertj-core dependency throughout Galasa to get integration tests back in a healthy state.
> Revert assertj-core dependency in inttests

- .github/workflows/build.yaml
For https://github.com/galasa-dev/projectmanagement/issues/2085
Using secret names that are specific to the Galasa team means that when users fork this repository and set secrets in their forked repository, they have to set it to the same name which being Galasa specific, doesn't make sense. Updating the secret names to be more general so it makes sense for forked repos. Also removing the hard coded use of the `galasa-team` user as forks won't/shouldn't use this user.
> Change secret names to non Galasa specific so relevant for forks

- .github/workflows/build.yaml
- .github/workflows/pr-build.yaml
Recreating PR #215 as not all commits were signed.
For https://github.com/galasa-dev/projectmanagement/issues/2085
- Skip certain steps if the workflow is being run by a fork
- Check required secrets are configured before proceeding with the workflow
- Replace some hard coded values with environment variables
> Iss2085 - Add extra check for forks running the workflows

- galasa-inttests-parent/build.gradle
For https://github.com/galasa-dev/projectmanagement/issues/2054
- Remove explicit versions in build.gradle (use galasa-bom versions)
- This upgrades the assertj-core version
- Ensures consistent version of assertj-core used throughout Galasa
> Iss2054 - Upgrade assertj-core version

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDocker.java
Since completing story https://github.com/galasa-dev/projectmanagement/issues/1888 the images have been cleared out of the `docker_proxy_cache` namespace in Harbor, so this test has been failing to find the `httpd` image it requires. This change updates the test to use GHCR as the Docker registry to attempt to grab images from for testing.
> Update the Docker registry for the DockerLocalJava11Ubuntu test

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDocker.java
As per this [PR in the Galasa repo](https://github.com/galasa-dev/galasa/pull/208), a fully qualified image name for the 'busybox' Docker image needs to be provided via CPS or the default of `library/busybox:latest` will be used. The image we want to use is at ghcr.io/galasa-dev/busybox:1.36.1 so we need to provide it to the child ecosystem in the test code so the DockerManagerIVT has access to it.
> Provide docker CPS properties to child ecosystem

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava11Ubuntu.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava11Ubuntu.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava11Ubuntu.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava11Ubuntu.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos3270/local/Zos3270LocalJava11Ubuntu.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosTso/local/ZosTsoLocalJava11Ubuntu.java
Part of story https://github.com/galasa-dev/projectmanagement/issues/2189
I have set up a new CronJob on cicsk8s that runs the CICSTSManagerIVT, CEMTManagerIVT, CedaManagerIVT, Zos3270IVT, ZosManagerIVT and ZosManagerTSOCommandIVT on prod1 daily at 6am. This is the equivalent of the tests I have removed from the schedule by commenting out their `@Test` annotations (the only difference is these tests spin up a "local Galasa ecosystem" on a Linux VM and run the IVT there, instead of directly on prod1). 
I have removed these tests from the schedule on the regression-run to 1) reduce the load on the Linux VMs 2) reduce the number of tests using the old mechanism, to hopefully reduce the likelihood of tests getting stuck and holding up the whole regression-run.
For the same reasons, I have …
> Iss2189 - Remove inttests that have been replaced by an IVT

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/isolated/ZosLocalJava11UbuntuIsolated.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/mvp/ZosLocalJava11UbuntuMvp.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava11UbuntuRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava11UbuntuZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/isolated/ZosBatchLocalJava11UbuntuIsolatedRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/isolated/ZosBatchLocalJava11UbuntuIsolatedZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/mvp/ZosBatchLocalJava11UbuntuMvpRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/mvp/ZosBatchLocalJava11UbuntuMvpZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava11UbuntuRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava11UbuntuZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/isolated/ZosFileLocalJava11UbuntuIsolatedRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/isolated/ZosFileLocalJava11UbuntuIsolatedZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/mvp/ZosFileLocalJava11UbuntuMvpRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/mvp/ZosFileLocalJava11UbuntuMvpZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava11UbuntuRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava11UbuntuZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/isolated/ZosFileDatasetLocalJava11UbuntuIsolatedRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/isolated/ZosFileDatasetLocalJava11UbuntuIsolatedZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/mvp/ZosFileDatasetLocalJava11UbuntuMvpRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/mvp/ZosFileDatasetLocalJava11UbuntuMvpZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosTso/local/isolated/ZosTsoLocalJava11UbuntuIsolated.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosTso/local/mvp/ZosTsoLocalJava11UbuntuMvp.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava11UbuntuRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava11UbuntuZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/isolated/ZosVSAMLocalJava11UbuntuIsolatedRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/isolated/ZosVSAMLocalJava11UbuntuIsolatedZosmf.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/mvp/ZosVSAMLocalJava11UbuntuMvpRse.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/mvp/ZosVSAMLocalJava11UbuntuMvpZosmf.java
Part of story https://github.com/galasa-dev/projectmanagement/issues/2189
I have set up a new CronJob on cicsk8s that runs the ZosFileManagerIVT, ZosFileDatasetManagerIVT, ZosVSAMManageIVT and ZosBatchManagerIVT on prod1 daily at 6am, with both the RSE API and z/OS MF implementations.
I have removed the equivalent inttests from the schedule by commenting out their @Test annotations, as we are trying to remove as many tests as possible that still require the local Galasa ecosystem install on the Linux VM.
I have removed the *Isolated and *Mvp variations of the tests also even though the IVTs can't test this - I discussed with @techcobweb that the Isolated and MVP tests should really be local Galasa tests, not remote ones on a Galasa service, as the Isolated/MVP zip can only be used …
> Iss2189 - Remove z/OS inttests from schedule as there are equivalent IVTs

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava11Ubuntu.java
For https://github.com/galasa-dev/projectmanagement/issues/2190
Part of the efforts to replace all the old inttests that rely on the Linux VMs with new tests.
- This PR removes the SimbankLocalJava11Ubuntu test from the inttest schedule.  It has been replaced by https://github.com/galasa-dev/simplatform/blob/main/.github/workflows/test.yaml so this inttest is no longer needed.
> Iss2190 - remove SimbankLocalJava11Ubuntu

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/isolated/ArtifactLocalJava11UbuntuIsolated.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/mvp/ArtifactLocalJava11UbuntuMvp.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/isolated/CoreLocalJava11UbuntuIsolated.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/mvp/CoreLocalJava11UbuntuMvp.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/isolated/SimBankLocalJava11UbuntuIsolated.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/mvp/SimBankLocalJava11UbuntuMvp.java
For https://github.com/galasa-dev/projectmanagement/issues/2190
Remove Isolated and MVP tests for the Core, Artifact and Simbank managers as they have been replicated in https://github.com/galasa-dev/isolated/pull/105
We will actually delete these test files at some point but for now while we're still converting them, its easier to be able to see the old tests.
> Remove Isolated and MVP tests for the Core, Artifact and Simbank

- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/offline/isolated/CompilationLocalOfflineJava11UbuntuIsolated.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/offline/mvp/CompilationLocalOfflineJava11UbuntuMVP.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/simbank/local/offline/isolated/CompilationLocalJava11UbuntuIsolated.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/simbank/local/offline/mvp/CompilationLocalJava11UbuntuMvp.java
- galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/simbank/local/online/CompilationLocalJava11Ubuntu.java
test: Removing old Compilation inttests that are no longer needed as they have been replaced by equivalent IVTs
> Removing old Compilation inttests

- .github/workflows/build.yaml
- .github/workflows/pr-build.yaml
- galasa-inttests-parent/build.gradle
- galasa-inttests-parent/dev.galasa.inttests/build.gradle
- galasa-inttests-parent/gradle.properties
For https://github.com/galasa-dev/projectmanagement/issues/2369
- Uplift Gradle version used in GitHub Actions workflows to 9.0.0 from 8.9.
- Uplift biz.aQute.bnd dependencies to version 7.1.0 as this version of the plugin is compatible with Gradle 9.0.0.
- Remove use of -b flag to point to location of build.gradle file as this has been removed in Gradle 9.
- Replace sourceCompatibility and targetCompatibility with Java toolchains as this is the recommended way to set the Java version.
> Iss2369 - Uplift gradle version used in build workflow to 9.0.0
