galasa-dev/integratedtests

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/voras/inttests/RunCommandlineTests.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/voras/inttests/RunDockerTests.java
galasa-inttests-parent/dev.galasa.inttests/src/main/resources/resources/settings.xml

Renaming to keep naming convention up to date

Rename Voras Galasa

---

README.md

update integration tests read me

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/SimBankIntegrationTests.java

Update simbank tests to use new package name

---

Jenkinsfile

enable bootstrap in folder properties

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Move to 0.7.0

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Move to 0.8.0-SNAPSHOT

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Move to 0.9.0-SNAPSHOT

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/VscodeIntegrationTests.java
galasa-inttests-parent/pom.xml

Signed-off-by: LukasMarivoetIBM <lukas.marivoet@ibm.com>

Integration testing vscode

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml

Make it easier to version update

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.9.0

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

version 0.10.0-SNAPSHOT

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.10.0

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.11.0-SNAPSHOT

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.11.0

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.12.0-SNAPSHOT

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.12.0

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.13.0-SNAPSHOT

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.13.0

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.14.0-SNAPSHOT

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.14.0

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/pom.xml
galasa-inttests-parent/pom.xml

Version 0.15.0-SNAPSHOT

---

.gitignore
Jenkinsfile.gradle
galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests/bnd.bnd
galasa-inttests-parent/dev.galasa.inttests/build.gradle
galasa-inttests-parent/dev.galasa.inttests/settings.gradle
galasa-inttests-parent/gradle.properties
galasa-inttests-parent/settings.gradle

Implemented gradle build. 
Didn't convert OBR.

Gradle Build

---

Jenkinsfile.gradle

reinstate the test catalog deployment

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests/build.gradle

allow for the test catalog to be built

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/AbstractArtifactLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava16Ubuntu.java

Add Artifact Manager local tests

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/kubernetes/ArtifactKubernetesJava08.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/kubernetes/CoreKubernetesJava08.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/kubernetes/SimBankKubernetesJava08.java

add testing areas

---

Jenkinsfile.gradle

Signed-off-by: James Davies <jdavies47@hotmail.co.uk>

Added a maven build to build the parent

---

Jenkinsfile.gradle
galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml

re remove the parent and change obr to base parent

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml

reenable the testcatalog generation

---

galasa-inttests-parent/settings.gradle

avoid jcenter due to certificate issues

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/AbstractHttpLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava11Ubuntu.java

Add http integration test

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava16Ubuntu.java

add http integration driver for all java versions

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/mvp/ArtifactLocalJava11UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/mvp/CoreLocalJava08UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/mvp/CoreLocalJava11UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/AbstractSimBankLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/mvp/SimBankLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/mvp/SimBankLocalJava11Ubuntu.java

Add SimBank integration tests

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos3270/AbstractZos3270Local.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos3270/local/Zos3270LocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos3270/local/Zos3270LocalJava11Ubuntu.java

Zos3270 tests

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/AbstractSimBankLocal.java

specify the simbank stream

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/mvp/SimBankLocalJava08UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/mvp/SimBankLocalJava11UbuntuMvp.java

Correct class names

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/AbstractZosLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/ZosLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/mvp/ZosLocalJava08UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/mvp/ZosLocalJava11UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos3270/local/Zos3270LocalJava11Ubuntu.java

Add zos manager inttest

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/isolated/CoreLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/isolated/CoreLocalJava11UbuntuIsolated.java

Add tests for the isolated zip

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/isolated/ArtifactLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/isolated/ArtifactLocalJava11UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/isolated/SimBankLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/isolated/SimBankLocalJava11UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/isolated/ZosLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zos/local/isolated/ZosLocalJava11UbuntuIsolated.java

add all the isolated tests

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/AbstractZosBatchLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/isolated/ZosLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/isolated/ZosLocalJava11UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/mvp/ZosLocalJava08UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/mvp/ZosLocalJava11UbuntuMvp.java

Integration Test for zosBatchManager

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/AbstractArtifactLocal.java

test pipeline

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/AbstractZosFileLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/isolated/ZosFileLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/isolated/ZosFileLocalJava11UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/mvp/ZosFileLocalJava08UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/mvp/ZosFileLocalJava11UbuntuMvp.java

Tests for zosFile.
Signed-off-by: Matthew Chivers <matthewchivers@outlook.com>

Added tests for ZosFile

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/AbstractZosBatchLocal.java

attempt to use RSE and z/OSMF

---

galasa-inttests-parent/dev.galasa.inttests/isolated/ZosFileLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/isolated/ZosFileLocalJava11UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/AbstractZosFileLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/AbstractZosFileDatasetLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/isolated/ZosFileDatasetLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/isolated/ZosFileDatasetLocalJava11UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/mvp/ZosFileDatasetLocalJava08UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/mvp/ZosFileDatasetLocalJava11UbuntuMvp.java

New Integration tests for PDS

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/AbstractZosVSAMLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava09Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava10Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/isolated/ZosVSAMLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/isolated/ZosVSAMLocalJava11UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/mvp/ZosVSAMLocalJava08UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/mvp/ZosVSAMLocalJava11UbuntuMvp.java

INT tests for VSAM

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/offline/mvp/CompilationLocalOfflineJava08UbuntuMVP.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/offline/mvp/CompilationLocalOfflineJava11UbuntuMVP.java

Corrected image capabilities to request an "isolated" image.
Signed-off-by: Matthew Chivers <matthewchivers@outlook.com>

Corrected capabilities

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava08UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava11UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava12UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava13UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava14UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava15UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava16UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/isolated/ZosBatchLocalJava08UbuntuIsolatedRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/isolated/ZosBatchLocalJava11UbuntuIsolatedRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/mvp/ZosBatchLocalJava08UbuntuMvpRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/mvp/ZosBatchLocalJava11UbuntuMvpRse.java

Signed-off-by: Jade Carino <jade.carino@ibm.com>

Add RSE tests back in

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/ceci/kubernetes/CECIKubernetesJava08.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava08UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava11UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava12UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava13UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava14UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava15UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava16UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/isolated/ZosBatchLocalJava08UbuntuIsolatedRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/isolated/ZosBatchLocalJava11UbuntuIsolatedRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/mvp/ZosBatchLocalJava08UbuntuMvpRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/mvp/ZosBatchLocalJava11UbuntuMvpRse.java

Signed-off-by: Jade Carino <jade.carino@ibm.com>

Remove CECIK8S inttest

---

tekton/pipe-inttests-repo-build.yaml
tekton/prun-main-inttests-build.yaml
tekton/task-inttests-repo-build.yaml

updated tekton files

---

README.md

Signed-off-by: James Davies <jdavies47@hotmail.co.uk>

Changed URLS for words matter

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/AbstractSimBankLocal.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava12Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava13Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava14Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava15Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava16Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/isolated/SimBankLocalJava08UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/isolated/SimBankLocalJava11UbuntuIsolated.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/mvp/SimBankLocalJava08UbuntuMvp.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/mvp/SimBankLocalJava11UbuntuMvp.java

Add additional diagnostic to solve the felix-cache problem

---

tekton/task-inttests-repo-build.yaml

tekton updates

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava11Ubuntu.java

tag tests that need to run in codecoverage

---

galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml

use new maven plugin for tags in catalog

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDockerUbuntuLocal.java

Signed-off-by: JansenGSY <keesjansen@Keess-MacBook-Pro.local>

Fixing apt issues for non-local build

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/kubernetes/ArtifactKubernetesJava08.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/artifact/local/ArtifactLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/ceci/local/CECILocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/kubernetes/CoreKubernetesJava08.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava08Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/core/local/CoreLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/http/local/HttpLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/kubernetes/SimBankKubernetesJava08.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/simbank/local/SimBankLocalJava11Ubuntu.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava11UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/local/ZosBatchLocalJava11UbuntuZosmf.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava11UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/local/ZosFileLocalJava11UbuntuZosmf.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava11UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/local/ZosFileDatasetLocalJava11UbuntuZosmf.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava11UbuntuRse.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/local/ZosVSAMLocalJava11UbuntuZosmf.java

tag tests for code coverage

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDockerUbuntuLocal.java

Signed-off-by: JansenGSY <keesjansen@Keess-MacBook-Pro.local>

Replaced apt with apt-get for package manager update

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDocker.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDockerUbuntuLocal.java

- Added in break so we dont wait 3 mins every time
- Added in Trace status for each min we're waiting

Fixing issues with docker service start wait. 

---

galasa-inttests-parent/dev.galasa.inttests/src/main/resources/resources/offlinebuild/AllManagers.txt
galasa-inttests-parent/dev.galasa.inttests/src/main/resources/resources/offlinebuild/MVPManagers.txt

Ensure the VTP manager can be loaded in MVP

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/local/DockerLocalJava11Ubuntu.java

Signed-off-by: JansenGSY <keesjansen@Keess-MacBook-Pro.local>

Readded code coverage tag for DockerManager tests

---

argocd/repositoryHelm/templates/integratedtests/maven-inttests.yaml

Set context root

---

argocd/repositoryHelm/templates/integratedtests/maven-inttests.yaml

correct syntax

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/AbstractZosBatchLocalRSE.java
galasa-inttests-parent/gradle.properties

Signed-off-by: Jade Carino <jade.carino@ibm.com>

Add GitHubIssue to 1 RSE test

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosBatch/AbstractZosBatchLocalRSE.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFile/AbstractZosFileLocalRSE.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosFileDataset/AbstractZosFileDatasetLocalRSE.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/zosVSAM/AbstractZosVSAMLocalRSE.java

Signed-off-by: Lewis James <lewisjames@Lewiss-MacBook-Pro.local>

Rolling back Jade's changes

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/compilation/simbank/local/online/CompilationLocalJava11Ubuntu.java

Signed-off-by: Aaron Jhaj <Aaron.Jhaj@ibm.com>

annotated compilation test with Github issue

---

galasa-inttests-parent/build.gradle

Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

bump framework version

---

.gitignore
build-locally.sh
galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml

Signed-off-by: Fiona Ampofo <64271621+Akyiaa@users.noreply.github.com>

updating maven plugin version

---

galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/RunCommandlineTests.java
galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/RunDockerTests.java

Signed-off-by: Aashir Siddiqui <aashir_sidiki@hotmail.com>
Refer to issue https://github.com/galasa-dev/projectmanagement/issues/1257

Removed @author tags from javadoc

---

.github/workflows/build.yaml
.github/workflows/pr-build.yaml
dockerfiles/dockerfile.inttests
galasa-inttests-parent/build.gradle

Fix Issue galasa-dev/projectmanagement#1941

Added PR and Main build workflows

---

.github/workflows/build.yaml
.github/workflows/pr-build.yaml

For issues
- galasa-dev/projectmanagement#1965
- galasa-dev/projectmanagement#1967

Added build log generation/uploading

---

.github/workflows/build.yaml
.github/workflows/pr-build.yaml

For https://github.com/galasa-dev/projectmanagement/issues/1982

Iss1982 - Add copyright

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/build.gradle
galasa-inttests-parent/gradle.properties

For https://github.com/galasa-dev/projectmanagement/issues/2079

Uplift development version to 0.40.0

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/build.gradle
galasa-inttests-parent/gradle.properties

For https://github.com/galasa-dev/projectmanagement/issues/2168

Bump development version to 0.41.0

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/build.gradle
galasa-inttests-parent/gradle.properties

For https://github.com/galasa-dev/projectmanagement/issues/2171

Bump development version to 0.42.0

---

galasa-inttests-parent/build.gradle
galasa-inttests-parent/dev.galasa.inttests.obr/pom.xml
galasa-inttests-parent/dev.galasa.inttests/build.gradle
galasa-inttests-parent/gradle.properties

For https://github.com/galasa-dev/projectmanagement/issues/2273

Bump development version to 0.44.0
